config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "/home/about" => "homes#about"
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  post "follow/:id" => "relationships#follow", as: "follow"
  post "unfollow/:id" => "relationships#unfollow", as: "unfollow"
  get "search" => "searches#search"
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  validates :name, uniqueness: true
  validates :name, length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50}

  def self.search(search,word)
    if search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  is_impressionable counter_cache: true
  


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy, :followings, :followers]


  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @books = @user.books
    @book = Book.new
    @users = User.all
    @set_relationship = current_user.relationships.new

    @user = User.find(params[:id])
    impressionist(@user, nil)

    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isroom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render "show_follow"
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render "show_follower"
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/45e42e65d8.js" crossorigin="anonymous"></script>
  </head>
  
  <body>
    <div>
      <div>
        <h2>User info</h2>
        <table class="table">
          <tr> <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></tr>
          <tr>
            <th>
              <p class="profile-name">name</p>
            </th>
            <th>
              <p><%= user.name %></p>
            </th>
          </tr>
          <tr>
            <th>
              <p class="profile-introduction">introduction<%= user.introduction %></p>
            </th>
            <th>
              <p><%= user.introduction %></p>
            </th>
          </tr>
          <tr>
            <th>
              <p>follows</p>
            </th>
            <th>
              <%= link_to user_followings_path(user) do %>
                <%= user.followings.count %>
              <% end %>
            </th>
          </tr>
          <tr>
            <th>
                <p>followers</p>
            </th>
            <th>
              <%= link_to user_followers_path(user) do %>
                <%= user.followers.count %>
              <% end %>
            </th>
          </tr>
        </table>
        <div class="row">
          <% if @user == current_user %>
            <%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
          <% else %>
            <% if current_user.following?(user) %>
              <%= link_to "Unfollow", user_relationships_path(user.id), method: :delete, class: "btn btn-info"  %>
            <% else %>
              <%= link_to "Follow", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
            <% end %>
          <% end %>
        </div>
      </div>
  </body>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/45e42e65d8.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <main>
      <% if @user.errors.any? %>
        <%= @user.errors.count %>eeors prohibited this obj from being saved:
        <% @user.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <h2>User info</h2>
            <%= form_with model:@user, local:true do |f| %>
              <div class="form-group">
              <label>Name</label>
                <%= f.text_field :name, autofocus: true, id:"inputName", class: "form-control"%>
              </div>
              <div class="form-group">
              <label>Image</label>
                <%= f.attachment_field :profile_image, placeholder:"プロフィール画像",  class: "form-control-file user_image" %>
              </div>
              <div class="form-group">
              <label>Introduction</label>
                <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", class: "form-control"%>
              </div>
              <div class="form-group">
                <%= f.submit "Update User", class: "btn btn-secondary"%>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </main>
     <footer>
      <div class='container mt-5'>
  	    <div class='row'>
    	    <div class='mx-auto'>
    		    <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/45e42e65d8.js" crossorigin="anonymous"></script>
  </head>
  
  <body>
    <main>
      <div class="container px-5 px-sm-0">
        <div class="row">
          <div class="col-md-3">
            <%= render "users/user", user: @user %>
            <%= render "books/book", book: @book %>
          </div>
        </div>
          <div class="col-md-8 offset-md-1">
            <h2>Users</h2>
              <table class="table">
                <thead>
                  <tr>
                    <th>image</th>
                    <th>name</th>
                    <th colspan="3"></th>
                  </tr>
                  <tbody>
                  <% @users.each do |user| %>
                  <tr>
                    <td>
                      <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                      
                    </td>
                    <td>
                      <%= user.name %>
                    </td>
                    <td>
                      <% if current_user.following?(user) %>
                        <%= link_to "Unfollow", user_relationships_path(user.id), method: :delete %>
                      <% else %>
                        <%= link_to "Follow", user_relationships_path(user.id), method: :post %>
                      <% end %>
                    </td>
                    <td>
                       <%= link_to "Show", user_path(user) %>
                    </td>
                  </tr>
                  <% end %>
                  </tbody>
                </thead>
              </table>
          </div>
      </div>
    </main>
     <footer>
      <div class='container mt-5'>
  	    <div class='row'>
    	    <div class='mx-auto'>
    		    <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>

app/views/users/show.html.erb
  <body>
    <main>
      <div class="container px-5 px-sm-0">
        <div class="row">
          <div class="col-md-3">

            <%= render "users/user", user: @user %> <br>
           
            <% unless @user.id == current_user.id %>
              <% if current_user.following?(@user) && @user.following?(current_user) %>
              <% if @isRoom == true %>
                <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary btn-lg">チャットへ</a></p>
              <% else %>
                <%= form_for @room do |f| %>
                  <%= fields_for @entry do |e| %>
                    <%= e.hidden_field :user_id, value: @user.id %>
                  <% end %>
                  <%= f.submit "チャットを始める", class: "btn btn-primary btn-lg user-show-chat" %>
                <% end %>
              <% end %>
              <% end %>
            <% end %>
            
             <%= render "books/book", book: @book %>
            
          </div>
        </div>
          <div class="col-md-8 offset-md-1">
            <h2>Books</h2>
              <table class="table table-hover table-inverse">
                <thead>
                  <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>
                <tbody>
                  <% @books.each do |book| %>
                    <tr>
                      <td>
                        <%= link_to @user_path do %>
                          <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                        <% end %>
                      </td>
                      <td>
                        <p><%= link_to book.title, book_path(book.id) %></p>
                      </td>
                      <td>
                        <p><%= book.body %></p>
                      </td>
                      <td class="favo-btn-<%= book.id %>">
                        <%= render 'favorites/favo', book: book %>
                      </td>
                      <td>
                        <%= link_to "#{book.book_comments.count}コメント", book_path(book.id) %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
          </div>
        </div>
      </main>
     <footer>
      <div class='container mt-5'>
  	    <div class='row'>
    	    <div class='mx-auto'>
    		    <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>