config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "/home/about" => "homes#about"
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  post "follow/:id" => "relationships#follow", as: "follow"
  post "unfollow/:id" => "relationships#unfollow", as: "unfollow"
  get "search" => "searches#search"
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}
  
  def self.search(search, word)
    if search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
    before_action :corrent_book, only: [:edit, :update]

  def corrent_book
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
    @user = current_user
    @book = Book.new
    @book_comment = BookComment.new
  end

  def show
    @book = Book.new
    @book1 = Book.find(params[:id])
    @user = @book1.user
    @book_comments = @book1.book_comments
    @book_comment = BookComment.new
    
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/45e42e65d8.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div>
      <div>
        <h2 class="mt-3">New book</h2>
          <%= form_with model: book, local:true do |f| %>
        <div class="form-group">
        <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
        <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.submit "Create Book", class: "btn btn-success" %>
        </div>
        <% end %>
      </div>
    </div>
  </body>

app/views/books/_favo.html.erb
<% if book.favorited_by?(current_user) %>
  <p class="text-primary">
    <%= link_to book_favorites_path(book), method: :delete, class: "text-danger" do %>
      ♥<%= book.favorites.count%>
    <% end %>
  </p>
  <% else %>
  <p class="text-danger">
    <%= link_to book_favorites_path(book), method: :book, class: "text-primary" do %>
      ♥<%= book.favorites.count %>
    <% end %>
  </p>
<% end %>

app/views/books/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/45e42e65d8.js" crossorigin="anonymous"></script>
  </head>
  
  <body>
    <main>
      <% if @book.errors.any? %>
        <%= @book.errors.count %>error prohibited this obj from being saved:
        <% @book.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <h1>Editing Book</h1>
            <%= form_with model: @book, local: true do |f| %>
            <div class="form-group">
              <label>Title</label>
              <%= f.text_field :title, class: "form-control"%>
            </div>
            <div class="form-group">
              <label>Opinion</label>
              <%= f.text_area :body, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.submit "Update Book", class: "btn btn-success"%>
            </div>
            <% end %>
            <%= link_to "Show", book_path(@book) %>
              |
            <a href="/books">Back</a>
          </div>
        </div>
      </div>
    </main>
    <footer>
      <div class='container mt-5'>
  	    <div class='row'>
    	    <div class='mx-auto'>
    		    <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/books/index.html.erb
    <main>
      <% if @book.errors.any? %>
        <%= @book.errors.count %>eeors prohibited this obj from being saved:
        <% @book.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <div class="container px-5 px-sm-0">
        <div class="row">
          <div class="col-md-3">
            <%= render "users/user", user: @user %>
            <%= render "books/book", book: @book %>
          </div>
        </div>
          <div class="col-md-8 offset-md-1">
            <h2>Books</h2>
            <table class="table table-hover table-inverse">
              <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%= link_to user_path(book.user) do %>
                      <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40"%>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to book.title, book_path(book.id) %>
                  </td>
                  <td>
                    <%= book.body %>
                  </td>
                  <td class="favo-btn-<%= book.id %>">
                    <%= render 'favorites/favo', book: book %>
                  </td>
                  <td>
                    <%= link_to "#{book.book_comments.count}コメント", book_path(book.id) %>
                  </td>
                  <td>

                  </td>
                </tr>
                <tr></tr>
              <% end %>
              </tbody>
            </table>
          </div>
      </div>
    </main>
    <footer>
      <div class='container mt-5'>
  	    <div class='row'>
    	    <div class='mx-auto'>
    		    <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit "Create Book" %>
<% end %>

app/views/books/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/45e42e65d8.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <main>
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <%= render "users/user", user: @book1.user %>
            <%= render "books/book", book: @book %>
          </div>
        </div>
          <div class="col-md-8 offset-md-1">
            <h2>Book detail</h2>
            <table class="table">
              <tbody>
                <tr>
                  <td>
                      <%= link_to user_path(@user) do %>
                        <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40"%> <br>
                      <% end %>
                      <%= link_to @user.name, user_path(@user) %>
                  </td>
                  <td>
                    <%= link_to @book1.title, book_path(@book1)%>
                  </td>
                  <td>
                    <%= @book1.body %>
                  </td>
                  <td>
                    <% if @user == current_user %>
                      <%= link_to "Edit", edit_book_path(@book1), class: "btn btn-sm btn-success" %>
                    <% end %>
                  </td>
                  <td>
                    <% if @user == current_user %>
                      <%= link_to "Destroy", book_path(@book1), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %>
                    <% end %>
                  </td>
                  <td class="favo-btn-<%= @book1.id %>">
                    <%= render "favorites/favo", book: @book1 %>
                  </td>
                  <td>
                    コメント件数:<%= @book1.book_comments.count %>
                  </td>
                  <td>
                    <strong>観覧数：</strong>
                    <%= @user.impressions_count %>
                  </td>
                </tr>
              </tbody>
            </table>

          <div class="comment">
            <table>
                <%= render "book_comments/comment", book_comments: @book_comments%>
            </table>
          </div>
            <div class="new-comment">
              <%= render "book_comments/form", book: @book1, book_comment: @book_comment %>
            </div>
            </div>
          </div>

      </div>
    </main>
    <footer>
      <div class='container mt-5'>
  	    <div class='row'>
    	    <div class='mx-auto'>
    		    <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>
</html>