config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "/home/about" => "homes#about"
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  post "follow/:id" => "relationships#follow", as: "follow"
  post "unfollow/:id" => "relationships#unfollow", as: "unfollow"
  get "search" => "searches#search"
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}
  
  def self.search(search, word)
    if search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book


end

app/models/message.rb
class Message < ApplicationRecord

  validates :content, presence: true
  belongs_to :user
  belongs_to :room

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  
  is_impressionable
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  validates :name, uniqueness: true
  validates :name, length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50}

  def self.search(search,word)
    if search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  is_impressionable counter_cache: true
  


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
    before_action :corrent_book, only: [:edit, :update]

  def corrent_book
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
    @user = current_user
    @book = Book.new
    @book_comment = BookComment.new
  end

  def show
    @book = Book.new
    @book1 = Book.find(params[:id])
    @user = @book1.user
    @book_comments = @book1.book_comments
    @book_comment = BookComment.new
    
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/seaches_helper.rb
module SeachesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <script src="https://kit.fontawesome.com/45e42e65d8.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/45e42e65d8.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to " Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
            </li>
            <li>
              <%= link_to " Users", users_path, class: "fas fa-users nav-link text-light" %>
            </li>
            <li>
              <%= link_to " Books", books_path, class: "fas fa-book-open nav-link text-light"%>
            </li>
            <li>
              <%= link_to " logout", destroy_user_session_path, method: :delete,  class: "fas fa-sign-out-alt nav-link text-light" %>
            </li>
            <% else %>
            <li>
              <%= link_to " Home", root_path, class: "fas fa-home nav-link text-light" %>
            </li>
            <li>
              <%= link_to " About", home_about_path,  class: "fas fa-link nav-link text-light"%>
            </li>
            <li>
              <%= link_to " sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
            </li>
            <li>
              <%= link_to " login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>


    <%= flash[:notice] %>
     
     <div class="text-center">
    <% if user_signed_in? %>
      <%= form_tag(search_path, method: :get) do %>
      <%= text_field_tag (:word)%>
    <%= select_tag "range", options_for_select([["User", "1"], ["Book", "2"]]) %>
      <%= select_tag "search", options_for_select([["前方一致", "forward_match"], ["後方一致", "backward_match"], ["完全一致", "perfect_match"], ["部分一致", "partial_match"]]) %>
      <%= submit_tag "検索" %>
      <% end %>
    <% end %>
    </div>
  <main>
    <%= yield %>
  </main>
  </body>
</html>